/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package net.ofnir.gradle.vaadinpackagescanner

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

class VaadinPackageScannerPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("net.ofnir.gradle.vaadin-package-scanner")

        then:
        project.tasks.findByName("vaadinScanPackages") != null
    }
}
